# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedstats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribercount",
            name="user_agent",
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
