# Generated by Django 6.0.2 on 2026-02-25 21:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0044_chapter_section_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_draft", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("import_ref", models.TextField(max_length=64, null=True, unique=True)),
                ("card_image", models.CharField(blank=True, max_length=128, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guides_chapter_set",
                        to="blog.series",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="guides_chapter_set", to="blog.tag"
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChapterChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_draft", models.BooleanField()),
                ("is_notable", models.BooleanField(default=False)),
                ("change_note", models.TextField(blank=True, default="")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="guides.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64)),
                ("order", models.IntegerField(default=0)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("guide", "slug")},
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapters",
                to="guides.guidesection",
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="guides_chap_search__eb3811_gin"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("guide", "slug")},
        ),
    ]
