# Generated by Django 6.0.2 on 2026-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_copy_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="is_unlisted",
            field=models.BooleanField(default=False),
        ),
    ]
