# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20150713_0551"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"get_latest_by": "created", "ordering": ("-created",)},
        ),
    ]
