# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:03


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170926_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmark',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
