# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:45


import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_metadata_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmark",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
