# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:48


import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_search_document"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogmark",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="blog_blogma_search__45eeb9_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="blog_quotat_search__aa2d47_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="blog_entry_search__d62c3b_gin"
            ),
        ),
    ]
