# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_gin_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmark",
            name="metadata",
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name="entry",
            name="metadata",
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="metadata",
            field=models.JSONField(blank=True, default={}),
        ),
    ]
