# Generated by Django 3.1.2 on 2020-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_fix_simon_incutio_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="custom_template",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
