# Generated by Django 4.1.7 on 2023-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_series_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmark",
            name="link_url",
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name="blogmark",
            name="via_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
