# Generated by Django 5.0.2 on 2024-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_blogmark_link_url_alter_blogmark_via_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmark",
            name="use_markdown",
            field=models.BooleanField(default=False),
        ),
    ]
