# Generated by Django 5.1 on 2024-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_previous_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmark",
            name="use_markdown",
            field=models.BooleanField(
                default=False,
                help_text='Images can use the img element - set width="..." for a specific width and use class="blogmark-image" to center and add a drop shadow.',
            ),
        ),
    ]
