# Generated by Django 5.1.1 on 2024-10-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_blogmark_is_draft_entry_is_draft_quotation_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="blog.entry",
                    ),
                ),
            ],
        ),
    ]
