# Generated by Django 5.1.1 on 2025-03-26 05:34

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_quotation_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("slug", models.SlugField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("import_ref", models.TextField(max_length=64, null=True, unique=True)),
                ("card_image", models.CharField(blank=True, max_length=128, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("body", models.TextField()),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.series",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name_plural": "Notes",
                "ordering": ("-created",),
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"], name="blog_note_search__10f4f2_gin"
                    )
                ],
            },
        ),
    ]
