# Generated by Django 5.1.1 on 2025-04-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(
                blank=True, default="", help_text="Optional page title", max_length=255
            ),
        ),
    ]
