# Generated by Django 5.1.4 on 2025-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_note_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmark",
            name="title",
            field=models.CharField(
                blank=True, default="", help_text="Optional page title", max_length=255
            ),
        ),
    ]
