# Generated by Django 5.1.4 on 2025-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_blogmark_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="use_markdown",
            field=models.BooleanField(
                default=False,
                help_text='Images can use the img element - set width="..." for a specific width and use class="blogmark-image" to center and add a drop shadow.',
            ),
        ),
    ]
