# Generated by Django 6.0 on 2025-12-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_blogmark_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagMerge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "source_tag_name",
                    models.SlugField(help_text="The tag that was merged (and deleted)"),
                ),
                (
                    "destination_tag_name",
                    models.SlugField(
                        help_text="Name of destination tag at time of merge"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="JSON with affected primary keys for each content type",
                    ),
                ),
                (
                    "destination_tag",
                    models.ForeignKey(
                        help_text="The tag that items were merged into",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Merge",
                "verbose_name_plural": "Tag Merges",
                "ordering": ("-created",),
            },
        ),
    ]
