# Generated by Django 6.0.2 on 2026-02-18 18:49

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_tagmerge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("slug", models.SlugField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("import_ref", models.TextField(max_length=64, null=True, unique=True)),
                ("card_image", models.CharField(blank=True, max_length=128, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "beat_type",
                    models.CharField(
                        choices=[
                            ("release", "Release"),
                            ("til_new", "TIL"),
                            ("til_update", "TIL updated"),
                            ("research", "Research"),
                            ("tool", "Tool"),
                            ("playbook_update", "Playbook update"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("commentary", models.CharField(blank=True, max_length=500)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.series",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"], name="blog_beat_search__41b6d3_gin"
                    ),
                    models.Index(
                        fields=["beat_type", "created"],
                        name="blog_beat_beat_ty_fa140c_idx",
                    ),
                ],
            },
        ),
    ]
