# Generated by Django 6.0.2 on 2026-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="beat_type",
            field=models.CharField(
                choices=[
                    ("release", "Release"),
                    ("til_new", "TIL"),
                    ("til_update", "TIL updated"),
                    ("research", "Research"),
                    ("tool", "Tool"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
