# Generated by Django 6.0.2 on 2026-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_alter_beat_beat_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("message", models.TextField()),
                ("learn_more_url", models.URLField()),
                ("display_from", models.DateTimeField()),
                ("display_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "color_scheme",
                    models.TextField(
                        choices=[
                            ("warm", "Warm"),
                            ("lavender", "Lavender"),
                            ("sage", "Sage"),
                            ("slate", "Slate"),
                            ("gold", "Gold"),
                            ("rose", "Rose"),
                            ("ocean", "Ocean"),
                            ("copper", "Copper"),
                            ("plum", "Plum"),
                            ("mint", "Mint"),
                            ("sky", "Sky"),
                            ("moss", "Moss"),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
    ]
