# Generated by Django 6.0.2 on 2026-02-19 01:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_sponsormessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_draft", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64)),
                ("body", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="blog.guide",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created"),
                "unique_together": {("guide", "slug")},
            },
        ),
    ]
