# Generated by Django 6.0.2 on 2026-02-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0034_guide_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsormessage",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
