# Generated by Django 6.0.2 on 2026-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0036_add_museum_beat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="image_alt",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="beat",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
