# Generated by Django 6.0.2 on 2026-02-23 06:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0038_rename_til_new_to_til"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="card_image",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="import_ref",
            field=models.TextField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chapter",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.series",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="blog_chapte_search__10f7f3_gin"
            ),
        ),
    ]
