# Generated by Django 6.0.2 on 2026-02-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0039_chapter_card_image_chapter_import_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_draft", models.BooleanField()),
                ("is_notable", models.BooleanField(default=False)),
                ("change_note", models.TextField(blank=True, default="")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="blog.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
    ]
