# Generated by Django 6.0.2 on 2026-02-23 12:10

from django.db import migrations


def populate_chapter_changes(apps, schema_editor):
    Chapter = apps.get_model("blog", "Chapter")
    ChapterChange = apps.get_model("blog", "ChapterChange")
    for chapter in Chapter.objects.all():
        ChapterChange.objects.create(
            chapter=chapter,
            created=chapter.created,
            title=chapter.title,
            body=chapter.body,
            is_draft=chapter.is_draft,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0040_chapter_change"),
    ]

    operations = [
        migrations.RunPython(
            populate_chapter_changes,
            migrations.RunPython.noop,
        ),
    ]
