# Generated by Django 6.0.2 on 2026-02-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0042_use_timezone_now_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64)),
                ("order", models.IntegerField(default=0)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.guide",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("guide", "slug")},
            },
        ),
    ]
