# Generated by Django 6.0.2 on 2026-02-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0043_guidesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapters",
                to="blog.guidesection",
            ),
        ),
    ]
