# Generated by Django 6.0.2 on 2026-02-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0044_chapter_section_fk"),
        ("guides", "0002_copy_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="chapter",
            name="blog_chapte_search__10f7f3_gin",
        ),
        migrations.AlterUniqueTogether(
            name="guidesection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="guidesection",
            name="guide",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="guide",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="section",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="series",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="tags",
        ),
        migrations.DeleteModel(
            name="ChapterChange",
        ),
        migrations.DeleteModel(
            name="Guide",
        ),
        migrations.DeleteModel(
            name="GuideSection",
        ),
        migrations.DeleteModel(
            name="Chapter",
        ),
    ]
