# Generated by Django 6.0.2 on 2026-02-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0045_remove_guide_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsormessage",
            name="learn_more_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
