# Generated by Django 6.0.2 on 2026-03-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0046_add_sponsor_learn_more_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
