# Generated by Django 6.1 on 2026-09-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0049_add_comment_beat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="replacement_blogmark",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_entry",
                to="blog.blogmark",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="replacement_note",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_entry",
                to="blog.note",
            ),
        ),
        migrations.AlterField(
            model_name="blogmark",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
    ]
