# Generated by Django 6.1 on 2026-09-13 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0050_entry_replacement_blogmark_entry_replacement_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="replacement_blogmark",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_entry",
                to="blog.blogmark",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="replacement_note",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_entry",
                to="blog.note",
            ),
        ),
    ]
