# Generated by Django 6.1 on 2026-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0051_replacement_sources_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="poll_live_updates",
            field=models.BooleanField(
                default=False,
                help_text="Live blog mode: open pages check for new live updates every few seconds. Turn off when the event is over.",
            ),
        ),
    ]
