# Generated by Django 6.1 on 2026-10-09 01:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0051_replacement_sources_set_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("substack", "Substack"),
                            ("sponsor", "Monthly sponsors"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Original send date, not the public release date.",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Substack or GitHub source URL.", max_length=2048
                    ),
                ),
                ("card_image", models.URLField(blank=True, max_length=2048)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Monthly newsletter content in Markdown."
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="The content is publicly available, not sponsors only.",
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the entire listing, including its title and link.",
                    ),
                ),
                ("import_ref", models.TextField(blank=True, null=True, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created", "-pk"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"],
                        name="blog_newsle_search__824279_gin",
                    )
                ],
            },
        ),
    ]
