# Generated by Django 6.1 on 2026-10-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0052_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="preview_headings",
            field=models.TextField(
                blank=True,
                help_text="Public preview for sponsors-only issues. One plain-text heading per line.",
            ),
        ),
    ]
