# Generated by Django 6.1.1 on 2026-10-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0053_newsletter_preview_headings"),
        ("blog", "0053_remove_pasted_live_updates_js"),
    ]

    operations = []
