# Generated by Django 6.1.1 on 2026-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0054_merge_20261009_0407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="preview_headings",
            field=models.TextField(
                blank=True,
                help_text="Preview for monthly newsletter listings. One plain-text heading per line.",
            ),
        ),
    ]
