# Generated by Django 6.1.1 on 2026-10-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0055_newsletter_preview_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="subtitle",
            field=models.TextField(
                blank=True, help_text="Plain-text newsletter subheading."
            ),
        ),
    ]
