# Generated by Django 6.1 on 2026-09-23 20:16

import shortener.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", shortener.fields.LongURLField(max_length=100000)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
