# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:58


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=128, null=True)),
                ("path", models.CharField(blank=True, max_length=128, null=True)),
                ("target", models.CharField(blank=True, max_length=256, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="redirect",
            unique_together=set([("domain", "path")]),
        ),
    ]
